kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hdfs-master-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: "hdfs-master-pv-data"
