kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hdfs-node-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: "hdfs-node-pv-data"
