apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-conf
  labels:
    name: hdfs-conf
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
          <name>fs.defaultFS</name>
          <value>hdfs://hadoop-hdfs-master:9000/</value>
      </property>
      <property>
          <name>dfs.namenode.rpc-bind-host</name>
          <value>0.0.0.0</value>
      </property>
      <property>
          <name>hadoop.tmp.dir</name>
          <value>/root/hdfs/tmp</value>
      </property>
      <property>
          <name>hadoop.security.token.service.use_ip</name>
          <value>false</value>
      </property>
    </configuration>
  startnode.sh: |
    #!/usr/bin/env bash
    sed -i "s/HDFS_MASTER_SERVICE/$HDFS_MASTER_SERVICE/g" $HADOOP_HOME/etc/hadoop/core-site.xml
    sed -i "s/@HDOOP_YARN_MASTER@/$HDOOP_YARN_MASTER/g" $HADOOP_HOME/etc/hadoop/yarn-site.xml
    yarn-master
    HADOOP_NODE="${HADOOP_NODE_TYPE}"
    if [ $HADOOP_NODE = "datanode" ]; then
            echo "Start DataNode ..."
            hdfs datanode  -regular
            
    else
        if [  $HADOOP_NODE = "namenode" ]; then
            if [ ! -d "/root/hdfs/$HADOOP_NODE/current" ];then
              echo "NameNode Format ..."
      	      echo y|hdfs namenode -format;
            fi
            echo "Start NameNode ..."
            hdfs namenode
        else
            if [ $HADOOP_NODE = "resourceman" ]; then
                echo "Start Yarn Resource Manager ..."
                yarn resourcemanager
            else
                
                 if [ $HADOOP_NODE = "yarnnode" ]; then
                     echo "Start Yarn Resource Node  ..."
                     yarn nodemanager	
                 else			   
                    echo "not recoginized nodetype "
                 fi
            fi
        fi	
            
    fi
