apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-node-pv-data
  labels:
    name: hdfs-node-pv-data
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "node1-volume"
    readOnly: false
